name: Central Caravel User Project Makefile Sync

on:
  # 1. Automated Trigger: Triggered by a dispatch from caravel_user_project
  repository_dispatch:
    types: [caravel-user-project-push]
  # 2. Manual Trigger: Allows manual execution from the Actions tab
  workflow_dispatch:
    inputs:
      upstream_sha:
        description: 'Optional: Upstream commit SHA to use for the PR title'
        required: false
        default: 'latest'

jobs:
  sync_downstream_repos:
    runs-on: ubuntu-latest
    
    # 1. Define the list of repositories to update
    strategy:
      matrix:
        # REPLACE the list below with the full names of your target repos (e.g., chipfoundry/user-project-1)
        target_repo_full_name: 
          - chipfoundry/openframe_user_project
          - chipfoundry/caravel_user_sram
          - chipfoundry/caravel_user_project_analog
          - chipfoundry/caravel_user_Neuromorphic_X1_32x32
          - chipfoundry/serial_controller_example
          - chipfoundry/caravel_user_sram_32kb
          - chipfoundry/caravel_user_sram_16kb
    
    steps:
      # --- Setup & Authentication ---
      
      - name: Generate App Token
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: chipfoundry 

      - name: Set Up Git
        run: |
          git config --global user.name "Caravel-Sync-Bot"
          git config --global user.email "Caravel-Sync-Bot[${{ secrets.GH_APP_ID }}]@users.noreply.github.com"
          
      # 2. Checkout TARGET Downstream Repository (where changes will be applied)
      - name: Checkout Target Repo ${{ matrix.target_repo_full_name }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.target_repo_full_name }}
          token: ${{ steps.app_token.outputs.token }}
          path: target-repo
          fetch-depth: 0 

      # 3. Clone Upstream Repo to a temporary directory
      - name: Clone Upstream Caravel Repo
        uses: actions/checkout@v4
        with:
          repository: chipfoundry/caravel_user_project
          token: ${{ steps.app_token.outputs.token }}
          path: upstream-repo
          
      # --- Copy & Check ---
      - name: Copy Specific Files and Check for Changes
        id: copy_files
        run: |
          TARGET_DIR="target-repo"
          UPSTREAM_DIR="upstream-repo"
          
          # Set variables and change directory
          UPSTREAM_SHA=${{ github.event.client_payload.sha || github.event.inputs.upstream_sha }}
          cd $TARGET_DIR
          
          # 1. --- Copy Root Makefile ---
          # Use -f to force overwrite, replacing existing file or symlink
          cp -f ../$UPSTREAM_DIR/Makefile .
          
          # 2. --- Copy openlane/Makefile ---
          mkdir -p openlane 2>/dev/null || true
          # Use -f to force overwrite
          cp -f ../$UPSTREAM_DIR/openlane/Makefile openlane/
          
          # 3. --- Copy .github/workflows/user_project_ci.yml ---
          mkdir -p .github/workflows 2>/dev/null || true
          # Use -f to force overwrite
          cp -f ../$UPSTREAM_DIR/.github/workflows/user_project_ci.yml .github/workflows/
          
          # 4. --- Copy .github/scripts/get_designs.py ---
          mkdir -p .github/scripts 2>/dev/null || true
          # Use -f to force overwrite
          cp -f ../$UPSTREAM_DIR/.github/scripts/get_designs.py .github/scripts/
          
          # 5. Add ALL the specific files to staging
          git add Makefile \
                    openlane/Makefile \
                    .github/workflows/user_project_ci.yml \
                    .github/scripts/get_designs.py
          
          # 6. Check for a diff on staged files
          if git diff --cached --exit-code; then
            echo "sync_required=false" >> $GITHUB_OUTPUT
            echo "Skipping PR creation: No configuration changes detected."
          else
            echo "sync_required=true" >> $GITHUB_OUTPUT
          fi
          
          # Output variables for the next step (Create Pull Request)
          echo "UPSTREAM_SHA=$UPSTREAM_SHA" >> $GITHUB_OUTPUT
      
      # --- Pull Request Creation ---
      - name: Create Pull Request
        id: cpr
        if: steps.copy_files.outputs.sync_required == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app_token.outputs.token }}
          path: target-repo 
          reviewers: marwaneltoukhy, jdicorpo
          branch: bot/config-sync 
          
          commit-message: "Autosync: Update core config files (${{ steps.copy_files.outputs.UPSTREAM_SHA }})"
          title: "🤖 [Automated Sync] Update Core Configuration Files"
          body: |
            This is an automated Pull Request to sync the latest **Makefiles, CI workflow, and build script** from the `caravel_user_project` template. This PR will be continuously updated by the bot until it is merged.
            
            * Files updated: `Makefile`, `openlane/Makefile`, `.github/workflows/user_project_ci.yml`, `.github/scripts/get_designs.py`
            * Upstream Commit: `${{ steps.copy_files.outputs.UPSTREAM_SHA }}`
          base: main 
          labels: automation, config-sync
    
      - name: Notify Team via GitHub Assignment (Sends Email Notification)
        if: success() && steps.copy_files.outputs.sync_required == 'true'
        run: |
          echo "PR created: ${{ steps.cpr.outputs.pull-request-url }}"
          
          # The notification is handled by the 'reviewers' input in the previous step.
          # We just need to log success here. 
          # If you didn't use the 'reviewers' input, you could use the gh CLI:
          # gh pr edit ${{ steps.cpr.outputs.pull-request-url }} --add-reviewer your-team/team-name
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}
          
